twig:
    default_path: '%kernel.project_dir%/templates'
    # ...
    file_name_pattern: '*.twig'

when@test:
    twig:
        debug: true
        strict_variables: false
        exception_controller: null
